name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    steps:
      - uses: actions/checkout@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: |
            index.html
            *.html
            *.css
            *.js
            images/
            docs/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
