name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare pages directory
        run: |
          mkdir pages
          # Copy all root files (including dotfiles) into 'pages'
          cp -r .[!.]* * pages

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
