name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare site
        run: 
          mkdir output
          cp -r * output
          # If your site is in docs/, replace cp -r * output with:
          # cp -r docs/* output

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: output

      - uses: actions/deploy-pages@v1
